apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
    name: python-sample2
spec:
    version: "v1.0.0"
    image: "syedgaian/openfunctions:python"
    imageCredentials:
        name: registry-credentials
    build:
        builder: "openfunction/gcp-builder:v1"
        env:
            GOOGLE_FUNCTION_TARGET: "hello_world"
            GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
            GOOGLE_FUNCTION_SOURCE: "main.py"
        srcRepo:
            url: "https://github.com/syedgaian/openfunction-test.git"
            sourceSubPath: "."
            revision: "python"
    serving:
        template:
            containers:
                - name: function
                  imagePullPolicy: IfNotPresent
        triggers:
            http:
                port: 8080
                route:
                    gatewayRef:
                        name: custom-gateway-istio
                        namespace: openfunction
