apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
    name: testing-revision
    annotations:
        openfunction.io/revision-controller: enable
        openfunction.io/revision-controller-params: |
        type: source
        repo-type: github
        polling-interval: 1m
spec:
    version: "v1.0.0"
    image: "syedgaian/openfunctions:python"
    imageCredentials:
        name: registry-credentials
    build:
        builder: "openfunction/gcp-builder:v1"
        env:
            GOOGLE_FUNCTION_TARGET: "hello_world"
            GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
            GOOGLE_FUNCTION_SOURCE: "main.py"
        srcRepo:
            url: "https://github.com/syedgaian/openfunction-test.git"
            sourceSubPath: "."
            revision: "python"
            credentials:
                name: "git-repo-secret"
    serving:
        template:
            containers:
                - name: function
                  imagePullPolicy: IfNotPresent
        triggers:
            http:
                port: 8080
                route:
                    gatewayRef:
                        name: custom-gateway
                        namespace: openfunction
